- name: Download Ansible
  get_url:
    url: "https://updates.jenkins-ci.org/latest/ansible.hpi"
    dest: "/home/ec2-user/ansible.hpi"

- name: Download Ansible Tower
  get_url:
    url: "https://updates.jenkins-ci.org/latest/ansible-tower.hpi"
    dest: "/home/ec2-user/ansible-tower.hpi"

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"
  notify: restart tomcat
